spring:
  application:
    name: pnc-parcial-final-hotel

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hoteldb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

jwt:
  secret: ${JWT_SECRET:ZGVtby1zZWNyZXQta2V5LXBhcmEtcGFyY2lhbC1maW5hbC1ob3RlbC0yMDI2fg==}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}      # 15 minutos
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 dias
